# --- !Ups

create table people (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  PRIMARY KEY (id)
);

# --- create table "people" (
# ---   "id" bigint generated by default as identity(start with 1) not null primary key,
# ---   "name" varchar not null,
# ---   "age" int not null
# --- );

# --- !Downs
drop table people if exist;

# --- drop table "people" if exists;
